import type { FreelancerProfile, ClientProfile, Application, User } from '@/types'

export const DEMO_USER_FREELANCER: User = {
  id: 'demo-freelancer-001',
  email: 'alex@demo.com',
  role: 'freelancer',
  created_at: '2024-01-15T10:00:00Z',
}

export const DEMO_USER_CLIENT: User = {
  id: 'demo-client-001',
  email: 'client@acme.com',
  role: 'client',
  created_at: '2024-02-01T10:00:00Z',
}

export const DEMO_USER_ADMIN: User = {
  id: 'demo-admin-001',
  email: 'admin@provenhire.com',
  role: 'admin',
  created_at: '2024-01-01T10:00:00Z',
}

export const DEMO_FREELANCERS: FreelancerProfile[] = [
  {
    id: 'fl-001',
    user_id: 'demo-freelancer-001',
    name: 'Alex Rivera',
    skill_category: 'web-development',
    bio: 'Full-stack engineer with 8 years building SaaS products. I specialize in React, Next.js, and Node.js. Previously led engineering at two YC-backed startups. I write clean, tested, documented code and communicate proactively throughout every engagement.',
    hourly_rate: 120,
    test_score: 94,
    status: 'approved',
    loom_url: 'https://loom.com/demo',
    avatar_url: null,
    portfolio_url: 'https://alexrivera.dev',
    years_experience: 8,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 'fl-002',
    user_id: 'u-002',
    name: 'Priya Sharma',
    skill_category: 'design',
    bio: 'Product designer focused on B2B SaaS. Expert in Figma, design systems, and user research. I have shipped interfaces used by over 200,000 people and obsess over the details that make products feel effortless. My test score reflects my systematic approach to UX.',
    hourly_rate: 95,
    test_score: 97,
    status: 'approved',
    loom_url: null,
    avatar_url: null,
    portfolio_url: 'https://priya.design',
    years_experience: 6,
    created_at: '2024-01-18T10:00:00Z',
    updated_at: '2024-01-22T10:00:00Z',
  },
  {
    id: 'fl-003',
    user_id: 'u-003',
    name: 'Marcus Chen',
    skill_category: 'mobile-development',
    bio: 'iOS and Android engineer with a focus on performance and native feel. 7 years building apps with React Native and Swift. Shipped 12 apps to the App Store, two of which hit top 100 in their categories. I care deeply about smooth 60fps animations and battery efficiency.',
    hourly_rate: 110,
    test_score: 91,
    status: 'approved',
    loom_url: null,
    avatar_url: null,
    portfolio_url: null,
    years_experience: 7,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-25T10:00:00Z',
  },
  {
    id: 'fl-004',
    user_id: 'u-004',
    name: 'Sofia Okonkwo',
    skill_category: 'data-science',
    bio: 'ML engineer and data scientist specialising in NLP and recommendation systems. PhD in Computer Science from Stanford. I have built production ML pipelines at scale serving millions of predictions per day. I translate business problems into measurable ML solutions.',
    hourly_rate: 150,
    test_score: 99,
    status: 'approved',
    loom_url: null,
    avatar_url: null,
    portfolio_url: 'https://github.com/sofiaokonkwo',
    years_experience: 5,
    created_at: '2024-01-22T10:00:00Z',
    updated_at: '2024-01-27T10:00:00Z',
  },
  {
    id: 'fl-005',
    user_id: 'u-005',
    name: 'James Whitfield',
    skill_category: 'devops',
    bio: 'DevOps engineer and cloud architect. AWS Solutions Architect certified. I build infrastructure that scales, costs less, and never goes down. Expert in Terraform, Kubernetes, and CI/CD. I have reduced infrastructure costs by an average of 40% for my last five clients.',
    hourly_rate: 130,
    test_score: 88,
    status: 'approved',
    loom_url: null,
    avatar_url: null,
    portfolio_url: null,
    years_experience: 9,
    created_at: '2024-01-24T10:00:00Z',
    updated_at: '2024-01-29T10:00:00Z',
  },
  {
    id: 'fl-006',
    user_id: 'u-006',
    name: 'Emma Larsson',
    skill_category: 'writing',
    bio: 'Technical writer and content strategist for developer tools and SaaS products. I have written docs for APIs used by 50,000+ developers and blog content that has driven over 1M organic visits. I make complex technical concepts clear and compelling.',
    hourly_rate: 75,
    test_score: 93,
    status: 'approved',
    loom_url: null,
    avatar_url: null,
    portfolio_url: 'https://emmalarsson.com',
    years_experience: 5,
    created_at: '2024-01-26T10:00:00Z',
    updated_at: '2024-01-31T10:00:00Z',
  },
  {
    id: 'fl-007',
    user_id: 'u-007',
    name: 'David Kim',
    skill_category: 'marketing',
    bio: 'Growth marketer with a track record in B2B SaaS. Former Head of Growth at two Series A startups. I run paid acquisition, SEO, and lifecycle email simultaneously and attribute revenue to each channel accurately. I only work on strategies I can measure.',
    hourly_rate: 100,
    test_score: 86,
    status: 'approved',
    loom_url: null,
    avatar_url: null,
    portfolio_url: null,
    years_experience: 6,
    created_at: '2024-01-28T10:00:00Z',
    updated_at: '2024-02-02T10:00:00Z',
  },
  {
    id: 'fl-008',
    user_id: 'u-008',
    name: 'Aisha Patel',
    skill_category: 'web-development',
    bio: 'Frontend engineer specialising in performance and accessibility. I build React and Vue applications that score 100 on Lighthouse and work for everyone, including users with disabilities. 5 years of experience shipping production UIs at fintech companies.',
    hourly_rate: 90,
    test_score: 92,
    status: 'approved',
    loom_url: null,
    avatar_url: null,
    portfolio_url: 'https://aishapatel.io',
    years_experience: 5,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-05T10:00:00Z',
  },
  {
    id: 'fl-009',
    user_id: 'u-009',
    name: 'Carlos Mendez',
    skill_category: 'video-editing',
    bio: 'Video editor and motion designer for tech brands and SaaS companies. I specialise in product demos, explainer videos, and social content that actually converts. My edits have been used in campaigns that generated over $2M in pipeline.',
    hourly_rate: 65,
    test_score: 89,
    status: 'approved',
    loom_url: null,
    avatar_url: null,
    portfolio_url: 'https://carlosmendez.video',
    years_experience: 4,
    created_at: '2024-02-03T10:00:00Z',
    updated_at: '2024-02-07T10:00:00Z',
  },
  {
    id: 'fl-010',
    user_id: 'u-010',
    name: 'Hannah Johansson',
    skill_category: 'design',
    bio: 'Brand designer and illustrator. I create visual identities that stand out — logos, design systems, marketing assets, and illustration. Former creative director at a Stockholm agency. I approach every project with strategic thinking first and aesthetics second.',
    hourly_rate: 85,
    test_score: 95,
    status: 'approved',
    loom_url: null,
    avatar_url: null,
    portfolio_url: 'https://hannah.design',
    years_experience: 7,
    created_at: '2024-02-05T10:00:00Z',
    updated_at: '2024-02-09T10:00:00Z',
  },
]

export const DEMO_PENDING_APPLICATIONS = [
  {
    id: 'app-pending-001',
    test_fee_paid: true,
    submitted_at: '2024-03-10T09:00:00Z',
    reviewed_at: null,
    reviewer_notes: null,
    status: 'pending' as const,
    freelancer_profiles: {
      id: 'fl-pending-001',
      name: 'Tom Bradley',
      skill_category: 'web-development',
      bio: 'Backend engineer with 4 years in Node.js and PostgreSQL. Built microservices for e-commerce platforms.',
      hourly_rate: 80,
      loom_url: 'https://loom.com/share/demo123',
      test_score: null,
      years_experience: 4,
    },
  },
  {
    id: 'app-pending-002',
    test_fee_paid: true,
    submitted_at: '2024-03-11T14:00:00Z',
    reviewed_at: null,
    reviewer_notes: null,
    status: 'pending' as const,
    freelancer_profiles: {
      id: 'fl-pending-002',
      name: 'Nina Kowalski',
      skill_category: 'design',
      bio: 'UX designer with 3 years of experience in B2C mobile apps. Portfolio includes work for two fintech startups.',
      hourly_rate: 70,
      loom_url: 'https://loom.com/share/demo456',
      test_score: null,
      years_experience: 3,
    },
  },
  {
    id: 'app-pending-003',
    test_fee_paid: false,
    submitted_at: '2024-03-12T11:30:00Z',
    reviewed_at: null,
    reviewer_notes: null,
    status: 'pending' as const,
    freelancer_profiles: {
      id: 'fl-pending-003',
      name: 'Raj Gupta',
      skill_category: 'data-science',
      bio: 'Data analyst transitioning to ML. Strong Python and pandas skills, currently completing fast.ai course.',
      hourly_rate: 55,
      loom_url: null,
      test_score: null,
      years_experience: 2,
    },
  },
]

export const DEMO_CLIENT_PROFILE: ClientProfile = {
  id: 'cp-001',
  user_id: 'demo-client-001',
  company_name: 'Acme Corp',
  subscription_status: 'active',
  stripe_customer_id: 'cus_demo',
  created_at: '2024-02-01T10:00:00Z',
}

export const DEMO_FREELANCER_PROFILE = DEMO_FREELANCERS[0] as FreelancerProfile

export const DEMO_FREELANCER_APPLICATION: Application = {
  id: 'app-001',
  freelancer_id: 'fl-001',
  test_fee_paid: true,
  stripe_payment_intent_id: 'pi_demo',
  submitted_at: '2024-01-15T10:00:00Z',
  reviewed_at: '2024-01-20T10:00:00Z',
  reviewer_notes: 'Excellent technical skills. Strong communication.',
  status: 'approved',
}

export const DEMO_INQUIRIES = [
  {
    id: 'inq-001',
    client_id: 'cp-001',
    freelancer_id: 'fl-002',
    message: 'Hi Priya, we are looking for a designer to redesign our onboarding flow. Would love to chat.',
    created_at: '2024-03-01T10:00:00Z',
    freelancer_profiles: { name: 'Priya Sharma', skill_category: 'design' },
  },
  {
    id: 'inq-002',
    client_id: 'cp-001',
    freelancer_id: 'fl-001',
    message: 'Alex, we need help building a new API integration. Are you available for a 2-week engagement?',
    created_at: '2024-03-05T14:00:00Z',
    freelancer_profiles: { name: 'Alex Rivera', skill_category: 'web-development' },
  },
]

export const DEMO_STATS = {
  total_freelancers: 10,
  pending_applications: 3,
  total_clients: 47,
  monthly_revenue: 4653,
}
